name: Azkaban
safe: true
lsi: false
pygments: true

tagline: "Open-source Workflow Manager"
image: "img/app.png"
repo: "azkaban/azkaban2"
docs: "/"

author :
  name : Richard Park
  email : rpark@linkedin.com
  github : rbpark

